all:
	$(CXX) -g -DNO_PYTHON -DNO_UCHARDET -I. -I../src/serviceapp/ ../src/serviceapp/wrappers.cpp ../src/serviceapp/m3u8.cpp ../src/serviceapp/common.cpp -lssl -lcrypto explore_m3u8.cpp -o explore_m3u8
